# proxmox VM settings
proxmox_vm_ubuntu_version: jammy
proxmox_vm_ram: 4096                                  # How much RAM to give each VM
proxmox_vm_cores: 2                                   # How many processors to give each VM
proxmox_vm_network_bridge: vmbr0                      # Which network to attach to each VM
proxmox_vm_disk0_size: 20                             # Size of the primary (system) disk on each VM in gigabytes
proxmox_vm_disk1_size: 60                             # Size of the secondary (data) disk on each VM in gigabytes
proxmox_storage: local-lvm
proxmox_iso_storage: local
proxmox_host_username: root@pam
proxmox_host_password: password

# Terraform
terraform_dir: ~/.terraform/homelab-builder

# VM Node settings
vm_username: ubuntu
vm_public_key: /full/path/to/ssh-key.pub
vm_private_key: /full/path/to/ssh-key
vm_network_gateway: 192.168.1.1

# Top level homelab domain - URL's for all services will be a subdomain of this
# For example, if dns_domain = example.com, gitea would be hosted at gitea.example.com
dns_domain: home.example.com
email: foobar@example.com

# Docker hub login details (to get around rate limits)
docker_hub_username:
docker_hub_password:
docker_hub_email:

# Distributed Storage
distributed_storage: "glusterfs" # 'ceph' or 'glusterfs'
distributed_storage_root: "/var/data"

# Ceph Configuration
ceph_dashboard_username: "username"
ceph_dashboard_password: "password"

# GlusterFS Configuration
gluster_brick_name: gluster
gluster_brick_dir: "/gluster-brick"
gluster_mount_dir: "{{ distributed_storage_root }}"

# Common recipe ENV
common_env_default:
  DOMAIN_NAME: "{{ dns_domain }}"

# recipe configs
recipes_default:
  authentik:
    enabled: true
    domain: "https://authentik.{{ dns_domain }}"
    api_base_url: "https://authentik.{{ dns_domain }}/api/v3"
    env:
      AUTHENTIK_BOOTSTRAP_EMAIL:
      AUTHENTIK_BOOTSTRAP_PASSWORD:
      AUTHENTIK_BOOTSTRAP_TOKEN:
  cloudflared:
    enabled: true
    env:
      TUNNEL_TOKEN:
  keepalived:
    enabled: true
    version: 2.0.20
  traefik:
    enabled: true
    auth_app_settings:
      app_name: Traefik Dashboard
      app_slug: traefik
      app_icon: traefik.png
      domain: traefik.{{ dns_domain }}
    localIps: "127.0.0.1/32,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"
    cloudflareIps: "173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22"
    env:
      DOMAIN_NAME: "{{ dns_domain }}"
  whoami:
    enabled: true
    auth_app_settings:
      app_name: WhoAmI Debugger
      app_slug: whoami
      app_icon: whoami.png
      domain: whoami.{{ dns_domain }}