---
# These are the physical proxmox hosts that you will be using to deploy your swarm nodes on to. There can be one
# or many of these defined.
proxmox_servers:
  hosts:
    # Example configuration below
    #  my-proxmox-host-1:
    #    ansible_host: 192.168.1.2
    #    ansible_user: root
    pve-1:
      ansible_host: 192.168.1.11
      ansible_user: root
    pve-2:
      ansible_host: 192.168.1.12
      ansible_user: root
    pve-3:
      ansible_host: 192.168.1.13
      ansible_user: root

# These are the swarm nodes that will be built and deployed to your proxmox hosts.
# There must be at least one node defined in the `cluster_nodes_master` group. Ansible will run the bootstrapping of the
# swarm on the first node in this group.
# There must be one node defined in the `storage_nodes` group. Ansible will run the bootstrapping of the
# storage on the first node in this group.
cluster_nodes:
  # Example configuration below
  # homelab-dev-1:
  #   vm_id: 3001
  #   ansible_host: 192.168.10.211
  #   ansible_ssh_private_key_file: "{{ compute_node.private_key }}"
  #   mac: "52:54:00:31:02:11"
  #   proxmox_node: pve-1
  #   keepalived_priority: 101 # required for `cluster_nodes_master` group
  #   node_cores_override: 6 # optional: override the amount of CPU cores on a per node basis
  children:
    compute_nodes:
      children:
        cluster_nodes_master:
          hosts:
            homelab-1:
              vm_id: 3001
              ansible_host: 192.168.1.211
              ansible_ssh_private_key_file: "{{ compute_node.private_key }}"
              mac: "52:54:00:31:02:11"
              proxmox_node: pve-1
              keepalived_priority: 101
              node_cores_override: 6
            homelab-2:
              vm_id: 3002
              ansible_host: 192.168.1.212
              ansible_ssh_private_key_file: "{{ compute_node.private_key }}"
              mac: "52:54:00:31:02:12"
              proxmox_node: pve-3
              keepalived_priority: 102
            homelab-3:
              vm_id: 3003
              ansible_host: 192.168.1.213
              ansible_ssh_private_key_file: "{{ compute_node.private_key }}"
              mac: "52:54:00:31:02:13"
              proxmox_node: pve-2
              keepalived_priority: 103
        cluster_nodes_workers:
          hosts:
            homelab-4:
              vm_id: 3004
              ansible_host: 192.168.1.214
              ansible_ssh_private_key_file: "{{ compute_node.private_key }}"
              mac: "52:54:00:31:02:14"
              proxmox_node: pve-1
            homelab-5:
              vm_id: 3005
              ansible_host: 192.168.1.215
              ansible_ssh_private_key_file: "{{ compute_node.private_key }}"
              mac: "52:54:00:31:02:15"
              proxmox_node: pve-3
            homelab-6:
              vm_id: 3006
              ansible_host: 192.168.1.216
              ansible_ssh_private_key_file: "{{ compute_node.private_key }}"
              mac: "52:54:00:31:02:16"
              proxmox_node: pve-2
    storage_nodes:
      hosts:
        homelab-storage:
          vm_id: 3007
          ansible_host: 192.168.1.217
          ansible_ssh_private_key_file: "{{ compute_node.private_key }}"
          mac: "52:54:00:31:02:17"
          proxmox_node: pve-1
