- name: ensure {{ distributed_storage_root }}/stack exists
  file:
    path: "{{ distributed_storage_root }}/stack"
    state: directory

- name: ensure {{ distributed_storage_root }}/appdata exists
  file:
    path: "{{ distributed_storage_root }}/appdata"
    state: directory

- name: run the recipe-generator
  include_tasks: generate-recipe.yml
  vars:
    requested_recipe: "{{ recipe }}"

- include_tasks: "recipes/{{ recipe }}/stack/bootstrap.yml"
  with_first_found:
    - files:
        - "recipes/{{ recipe }}/stack/bootstrap.yml"
      skip: true

- name: "{{ recipe }} --> deploy recipe stack"
  docker_stack:
    state: present
    name: "{{ recipe }}"
    compose: "{{ distributed_storage_root }}/stack/{{ recipe }}/docker-compose.yml"
    with_registry_auth: yes
  register: _result
  until: _result.failed == false
  retries: 20 # retry X times
  delay: 30     # pause for X sec b/w each call

- name: "{{ recipe }} --> Test whether the stack is running as desired"
  shell: "docker stack ps {{ recipe }} --filter \"desired-state=running\"  --format \"{{'{{'}} .CurrentState {{'}}'}}\" | grep -v Running"
  register: _result
  until: _result.rc == 1
  failed_when: _result.rc != 1
  retries: 120 # retry X times
  delay: 5   # pause for X sec b/w each call

- include_tasks: "recipes/{{ recipe }}/stack/post-deploy.yml"
  with_first_found:
    - files:
        - "recipes/{{ recipe }}/stack/post-deploy.yml"
      skip: true