- name: ensure /var/data/stack exists
  file:
    path: /var/data/stack
    state: directory

- name: ensure /var/data/appdata exists
  file:
    path: /var/data/appdata
    state: directory

- name: run the recipe-generator
  include_tasks: generate-recipe.yml
  vars:
    requested_recipe: "{{ recipe }}"

- include_tasks: "recipes/{{ recipe }}/stack/bootstrap.yml"
  with_first_found:
    - files:
        - "recipes/{{ recipe }}/stack/bootstrap.yml"
      skip: true

- name: "{{ recipe }} --> deploy recipe stack"
  docker_stack:
    state: present
    name: "{{ recipe }}"
    compose: "/var/data/stack/{{ recipe }}/docker-compose.yml"
    with_registry_auth: yes
  register: _result
  until: _result.failed == false
  retries: 20 # retry X times
  delay: 30     # pause for X sec b/w each call

# Post deploy actions

- name: "{{ recipe }} --> Test whether the stack is running as desired"
  shell: "docker stack ps {{ recipe }} --filter \"desired-state=running\"  --format \"{{'{{'}} .CurrentState {{'}}'}}\" | grep -v Running"
  register: _result
  until: _result.rc == 1
  failed_when: _result.rc != 1
  retries: 60 # retry X times
  delay: 5   # pause for X sec b/w each call