---
env: "{{ lookup('env', 'ENVIRONMENT') }}"
dns_domain: "example.com"
terraform:
  dir: "~/.terraform/homelab-builder-{{ env }}/"

proxmox:
  host_username: root@pam
  host_password: password
  iso_storage: local
  disk_storage: local-lvm

cluster_node:
  cpu_cores: 1
  memory: 4096
  network_gateway: 192.168.1.1
  network_bridge: vmbr0
  ubuntu_version: noble
  disk0_size: 20
  disk1_size: 100
  username: ubuntu
  public_key: /Users/my-user/.ssh/some-key.pub
  private_key: /Users/my-user/.ssh/some-key

docker_hub:
  username:
  password:

runtime:
  type: docker
  docker:

  kubernetes:
    version: v1.30.2+k3s2

storage:
  engine: "ceph" # 'ceph' or 'glusterfs'
  root_dir: "/var/data"

  ceph:
    dashboard_username: username
    dashboard_password: password
  glusterfs:
    brick_name: gluster
    brick_dir: "/gluster-brick"

common_service_env:
  DOMAIN_NAME: "{{ dns_domain }}"

services:
  actual_budget:
    enabled: true
    auth_enabled: true
    auth_app_settings:
      app_name: Actual Budget
      app_slug: actual-budget
      app_icon: actual-budget.png
      domain: actual-budget.{{ dns_domain }}
    version: 25.1.0
  authentik:
    enabled: true
    domain: "https://authentik.{{ dns_domain }}"
    api_base_url: "https://authentik.{{ dns_domain }}/api/v3"
    env:
      AUTHENTIK_BOOTSTRAP_EMAIL:
      AUTHENTIK_BOOTSTRAP_PASSWORD:
      AUTHENTIK_BOOTSTRAP_TOKEN:
    version:
      postgres: 16-alpine
      redis: 7-alpine
      authentik: 2024.12.1
  cloudflared:
    enabled: true
    env:
      TUNNEL_TOKEN:
    version: latest
  gitea:
    enabled: true
    auth_enabled: true
    auth_app_settings:
      app_name: Gitea
      app_slug: gitea
      app_icon: gitea.png
      domain: gitea.{{ dns_domain }}
    env:
      DISABLE_REGISTRATION: true
    version:
      postgres: 14
      gitea: 1.22.6
  homepage:
    enabled: true
    auth_enabled: true
    auth_app_settings:
      app_name: Homepage
      app_slug: homepage
      app_icon: homepage.png
      domain: "{{ dns_domain }}"
    version: latest
  keepalived:
    enabled: true
    version: 2.0.20
  overseerr:
    enabled: true
    auth_enabled: true
    auth_app_settings:
      app_name: Overseerr
      app_slug: overseerr
      app_icon: overseerr.png
      domain: overseerr.{{ dns_domain }}
    version: latest
  portainer:
    enabled: true
    auth_enabled: true
    auth_app_settings:
      app_name: Portainer
      app_slug: portainer
      app_icon: portainer.png
      domain: portainer.{{ dns_domain }}
    version:
      agent: 2.21.5
      portainer: 2.21.5
  traefik:
    enabled: true
    auth_enabled: true
    auth_app_settings:
      app_name: Traefik Dashboard
      app_slug: traefik
      app_icon: traefik.png
      domain: traefik.{{ dns_domain }}
    env:
      CF_DNS_API_TOKEN: ""
      DOMAIN_NAME: "{{ dns_domain }}"
    localIps: "127.0.0.1/32,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"
    cloudflareIps: "173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22"
    version: v3.2
  whoami:
    enabled: true
    auth_enabled: true
    auth_app_settings:
      app_name: WhoAmI Debugger
      app_slug: whoami
      app_icon: traefik.png
      domain: whoami.{{ dns_domain }}
    version: v1.10

external_services:
  unraid:
    app_name: unraid
    app_icon: unraid.png
    domain: unraid.{{ dns_domain }}
    dest: "https://192.168.1.2"
  proxmox:
    app_name: proxmox
    app_icon: proxmox.png
    domain: proxmox.{{ dns_domain }}
    dest: "https://192.168.1.3:8006"