---
timezone: "Australia/Sydney"
env: "{{ lookup('env', 'ENVIRONMENT') }}"
dns_domain: "example.com"
private_service_rule: "!HeaderRegexp(`CF-Connecting-IP`, `.*`)"
entrypoint_ip: 192.168.10.210
terraform:
  dir: "~/.terraform/homelab-builder-{{ env }}/"

admin_user:
  name: 
  email: 

proxmox:
  host_username: root@pam
  host_password: password
  iso_storage: local
  disk_storage_master: bigdata
  disk_storage_worker: local-lvm

cluster_node:
  cpu_cores: 1
  memory: 4096
  network_gateway: 192.168.1.1
  network_bridge: vmbr0
  ubuntu_version: noble
  disk0_size: 20
  disk1_size: 100 # master nodes only
  username: ubuntu
  public_key: /Users/my-user/.ssh/some-key.pub
  private_key: /Users/my-user/.ssh/some-key

docker_hub:
  username:
  password:

runtime:
  type: docker # Only 'docker' supported at the moment
  docker:
    keepalived:
      virtual_ip: "{{ entrypoint_ip }}"
  kubernetes: # Not implemented
    version: v1.30.2+k3s2

storage:
  engine: "ceph" # 'ceph' or 'glusterfs'
  root_dir: "/var/data"
  media_dir: "/mnt/external"
  owner: 1000
  group: 1000

  ceph:
    dashboard_username: username
    dashboard_password: password
  glusterfs:
    brick_name: gluster
    brick_dir: "/gluster-brick"

  external:
    nfs:
      # media:
      #   host: "192.168.1.2"
      #   source_path: "/mnt/media"
      # downloads:
      #   host: "192.168.1.8"
      #   source_path: "/mnt/downloads"


common_service_env:
  DOMAIN_NAME: "{{ dns_domain }}"
  PRIVATE_DOMAIN_NAME: "{{ private_dns_domain }}"

infrastructure_services:
  authentik:
    domain: "authentik.{{ dns_domain }}"
    enabled: true
    api_base_url: "http://127.0.0.1:9000/api/v3"
    env:
      AUTHENTIK_BOOTSTRAP_EMAIL:
      AUTHENTIK_BOOTSTRAP_PASSWORD:
      AUTHENTIK_BOOTSTRAP_TOKEN:
    version:
      postgres: 16-alpine
      redis: 7-alpine
      authentik: 2024.12.1
  cloudflared:
    enabled: true
    env:
      TUNNEL_TOKEN:
    version: latest
  crowdsec:
    enabled: true
    version:
      crowdsec: latest
      bouncer: latest
  keepalived:
    enabled: true
    version: 2.0.20
  traefik:
    domain: traefik.{{ dns_domain }}
    enabled: true
    public: true
    auth_enabled: true
    auth_app_settings:
      app_name: Traefik Dashboard
      app_slug: traefik
      app_icon_source: https://cdn.jsdelivr.net/gh/selfhst/icons/png/traefik.png
    env:
      CF_DNS_API_TOKEN: ""
      DOMAIN_NAME: "{{ dns_domain }}"
    localIps: "127.0.0.1/32,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"
    cloudflareIps: "173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22"
    version: v3.2

services:
  actual_budget:
    domain: actual-budget.{{ dns_domain }}
    enabled: true
    public: true
    auth_enabled: true
    auth_app_settings:
      app_name: Actual Budget
      app_slug: actual-budget
      app_icon_source: https://cdn.jsdelivr.net/gh/selfhst/icons/png/actual-budget.png
    version: 25.1.0
  gitea:
    domain: gitea.{{ dns_domain }}
    enabled: true
    public: true
    auth_enabled: true
    auth_app_settings:
      app_name: Gitea
      app_slug: gitea
      app_icon_source: https://cdn.jsdelivr.net/gh/selfhst/icons/png/gitea.png
    env:
      DISABLE_REGISTRATION: true
    version:
      postgres: 14
      gitea: 1.22.6
  homepage:
    domain: "{{ dns_domain }}"
    enabled: true
    public: true
    auth_enabled: true
    auth_app_settings:
      app_name: Homepage
      app_slug: homepage
      app_icon_source: https://cdn.jsdelivr.net/gh/selfhst/icons/png/homepage.png
    version: latest
  overseerr:
    domain: overseerr.{{ dns_domain }}
    enabled: true
    public: true
    auth_enabled: true
    auth_app_settings:
      app_name: Overseerr
      app_slug: overseerr
      app_icon_source: https://cdn.jsdelivr.net/gh/selfhst/icons/png/overseerr.png
    version: latest
  portainer:
    domain: portainer.{{ dns_domain }}
    enabled: true
    public: true
    auth_enabled: true
    auth_app_settings:
      app_name: Portainer
      app_slug: portainer
      app_icon_source: https://cdn.jsdelivr.net/gh/selfhst/icons/png/portainer.png
    version:
      agent: 2.21.5
      portainer: 2.21.5
  sabnzbd:
    domain: sabnzbd.{{ dns_domain }}
    enabled: true
    public: true
    auth_enabled: true
    auth_app_settings:
      app_name: SabNZBD
      app_slug: sabnzbd
      app_icon_source: https://cdn.jsdelivr.net/gh/selfhst/icons/png/sabnzbd.png
    version: latest
  whoami:
    domain: whoami.{{ dns_domain }}
    enabled: true
    public: true
    auth_enabled: true
    auth_app_settings:
      app_name: WhoAmI Debugger
      app_slug: whoami
      app_icon_source: https://cdn.jsdelivr.net/gh/selfhst/icons/png/traefik.png
    version: v1.10

external_services:
  unraid:
    domain: unraid.{{ dns_domain }}
    enabled: true
    public: true
    auth_enabled: true
    auth_app_settings:
      app_name: Unraid
      app_slug: unraid
      app_icon_source: https://cdn.jsdelivr.net/gh/selfhst/icons/png/unraid.png
  proxmox:
    domain: proxmox.{{ dns_domain }}
    enabled: true
    public: true
    auth_enabled: true
    auth_app_settings:
      app_name: Proxmox
      app_slug: proxmox
      app_icon_source: proxmox.png
    dest: "https://192.168.1.3:8006"
