- name: gather keepalived peers
  run_once: true
  set_fact:
    keepalived_peers: "{{ ansible_play_hosts|map('extract', hostvars, 'ansible_host')|flatten }}"
    run_once: true

- name: add ip_vs to /etc/modules
  lineinfile:
    dest: /etc/modules
    line: "ip_vs"
    state: present

- name: insert ip_vs into running kernel
  modprobe:
    name: ip_vs
    state: present

- name: create keepalived containers
  docker_container:
    name: "keepalived"
    image: "osixia/keepalived:{{ recipes.keepalived.version }}"
    capabilities: "NET_ADMIN"
    network_mode: "host"
    state: started
    restart: yes
    restart_policy: unless-stopped
    env:
      KEEPALIVED_INTERFACE: "eth0"
      KEEPALIVED_UNICAST_PEERS: "#PYTHON2BASH:[ '{{ \"', '\".join(keepalived_peers) }}' ]"
      KEEPALIVED_VIRTUAL_IPS: "{{ keepalived_virtual_ip }}"
      KEEPALIVED_PRIORITY: "{{ keepalived_priority | quote }}"
