---
- name: Gather keepalived peers
  run_once: true
  ansible.builtin.set_fact:
    keepalived_peers: "{{ ansible_play_hosts | map('extract', hostvars, 'ansible_host') | flatten }}"

- name: Add ip_vs to /etc/modules
  ansible.builtin.lineinfile:
    dest: /etc/modules
    line: "ip_vs"
    state: present

- name: Insert ip_vs into running kernel
  ansible.builtin.modprobe:
    name: ip_vs
    state: present

- name: Create keepalived containers
  ansible.builtin.docker_container:
    name: "keepalived"
    image: "osixia/keepalived:{{ keepalived.version }}"
    capabilities: "NET_ADMIN"
    network_mode: "host"
    state: started
    restart: true
    restart_policy: unless-stopped
    env:
      KEEPALIVED_INTERFACE: "eth0"
      KEEPALIVED_UNICAST_PEERS: "#PYTHON2BASH:[ '{{ \"', '\".join(keepalived_peers) }}' ]"
      KEEPALIVED_VIRTUAL_IPS: "{{ runtime.docker.keepalived.virtual_ip }}"
      KEEPALIVED_PRIORITY: "{{ keepalived_priority | quote }}"
