---
- name: Run the recipe-generator
  block:
    - name: "Create cloudflared stack dir"
      ansible.builtin.file:
        path: "{{ storage.root_dir }}/stack/cloudflared"
        state: directory
        mode: "0755"

    - name: "Create cloudflared appdata dir"
      ansible.builtin.file:
        path: "{{ storage.root_dir }}/appdata/cloudflared"
        state: directory
        mode: "0755"

    - name: "Copy docker-compose template file"
      ansible.builtin.template:
        force: true
        src: templates/cloudflared/stack/docker-compose.yml.j2
        dest: "{{ storage.root_dir }}/stack/cloudflared/docker-compose.yml"
        mode: "0600"
      changed_when: true
      vars:
        foo: "bar"

    - name: "Copy env file"
      ansible.builtin.copy:
        force: true
        src: files/cloudflared/stack/service.env
        dest: "{{ storage.root_dir }}/stack/cloudflared/.env"
        mode: "0600"

    - name: "Set cloudflared global env vars"
      ansible.builtin.lineinfile:
        path: "{{ storage.root_dir }}/stack/cloudflared/.env"
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      with_items: "{{ common_env | dict2items }}"
      when:
        - common_env is defined

    - name: "Set cloudflared specific env vars"
      ansible.builtin.lineinfile:
        path: "{{ storage.root_dir }}/stack/cloudflared/.env"
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      with_items: "{{ infrastructure_services.cloudflared.env | dict2items }}"
      when:
        - infrastructure_services.cloudflared.env is defined

- name: Ensure cloudflared stack is not deployed
  docker_stack:
    state: absent
    name: "cloudflared"
    compose: "{{ storage.root_dir }}/stack/cloudflared/docker-compose.yml"
    with_registry_auth: true
  when: not infrastructure_services.cloudflared.enabled
  register: _result
  until: _result.failed == false
  retries: 20 # retry X times
  delay: 30 # pause for X sec b/w each call

- name: Deploy cloudflared stack and verify stack running
  when: infrastructure_services.cloudflared.enabled
  block:
    - name: "Deploy recipe stack"
      ansible.builtin.docker_stack:
        state: present
        name: "cloudflared"
        compose: "{{ storage.root_dir }}/stack/cloudflared/docker-compose.yml"
        with_registry_auth: true
      register: _result
      until: _result.failed == false
      retries: 20 # retry X times
      delay: 30 # pause for X sec b/w each call

    - name: "Test whether the stack is running as desired"
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: set -o pipefail && docker stack ps cloudflared --filter "desired-state=running"  --format "{{ '{{' }} .CurrentState {{ '}}' }}" | grep -v Running
      register: _result
      until: _result.rc == 1
      failed_when: _result.rc != 1
      retries: 120 # retry X times
      delay: 5 # pause for X sec b/w each call
      changed_when: true
