---
- name: Ensure root_dir /stack dir exists
  ansible.builtin.file:
    path: "{{ storage.root_dir }}/stack"
    state: directory
    mode: "0775"

- name: Ensure root_dir /appdata dir exists
  ansible.builtin.file:
    path: "{{ storage.root_dir }}/appdata"
    state: directory
    mode: "0775"

# Setup baseline networking
- name: Create swarm networks
  block:
    - name: Create cloud-public network # noqa syntax-check[unknown-module]
      ansible.builtin.docker_network:
        name: cloud-public
        scope: swarm
        driver: overlay
        attachable: true

- name: Log into DockerHub (to avoid ratelimits)
  ansible.builtin.docker_login:
    username: "{{ docker_hub.username }}"
    password: "{{ docker_hub.password }}"
  when:
    - docker_hub.username is defined
    - docker_hub.password is defined

- name: Deploy traefik
  ansible.builtin.include_tasks:
    deploy-traefik.yml

- name: Deploy cloudflared
  ansible.builtin.include_tasks:
    deploy-cloudflared.yml

- name: Deploy authentik
  ansible.builtin.include_tasks:
    deploy-authentik.yml

- name: Add auth to traefik dashboard
  ansible.builtin.import_role:
    name: deploy/authentik-add-service # noqa role-name[path]
  vars:
    domain: "{{ infrastructure_services.traefik.domain }}"
    auth_enabled: "{{ infrastructure_services.traefik.auth_enabled }}"
    auth_app_settings: "{{ infrastructure_services.traefik.auth_app_settings }}"
