---
argument_specs:
  main:
    short_description: "Creates an auth stack for a service/endpoint in Authentik"
    options:
      domain:
        type: str
        description: Address for service
        default: ""
      auth_enabled:
        type: bool
        description: Is authentication enabled for service?
        default: true
      auth_app_settings:
        type: dict
        required: true
        options:
          type:
            type: str
            required: false
            default: proxy
            choices:
              - proxy
              - oauth2
          app_name:
            type: str
            required: true
          app_slug:
            type: str
            required: true
          app_icon_source:
            type: str
            required: true
          oauth_redirect_uri:
            type: str
            required: false 
            default: None
