---
# Install Docker
- name: Install Docker
  ansible.builtin.include_role:
    name: provision/node-install-docker # noqa role-name[path]

- name: Log into DockerHub (to avoid ratelimits)
  docker_login:
    username: "{{ docker_hub.username }}"
    password: "{{ docker_hub.password }}"
  when:
    - docker_hub.username is defined
    - docker_hub.password is defined

- name: Install CEPH for distributed storage
  ansible.builtin.include_role:
    name: provision/node-install-ceph # noqa role-name[path]
  when:
    - storage.engine == 'ceph'
    - hostvars[inventory_hostname_short]["group_names"] is contains("cluster_nodes_master")

- name: Install GlusterFS for distributed storage
  ansible.builtin.include_role:
    name: provision/node-install-glusterfs # noqa role-name[path]
  when:
    - storage.engine == 'glusterfs'
    - hostvars[inventory_hostname_short]["group_names"] is contains("cluster_nodes_master")

- name: Setup Keepalived for a shared virtual IP
  ansible.builtin.include_role:
    name: provision/node-install-keepalived # noqa role-name[path]
  when:
    - hostvars[inventory_hostname_short]["group_names"] is contains("cluster_nodes_master")

- name: Set dir permissions on root dir
  ansible.builtin.file:
    path: "{{ storage.root_dir }}"
    state: directory
    mode: "0777"
    owner: "nobody"
    group: "nogroup"
    recurse: true

- name: Setup NFS Server/Clients
  ansible.builtin.include_role:
    name: provision/node-install-nfs # noqa role-name[path]

- name: Mount external shares
  ansible.builtin.include_role:
    name: provision/node-mount-external-storage # noqa role-name[path]
