- name: Run Terraform
  delegate_to: localhost
  run_once: true
  block:
    - name: Run terraform init
      command: terraform init -upgrade
      args:
        chdir: "{{ terraform_dir }}"

    - name: Run terraform plan
      command: terraform plan
      args:
        chdir: "{{ terraform_dir }}"

    - name: Run terraform apply
      command: terraform apply -auto-approve
      args:
        chdir: "{{ terraform_dir }}"

- name: Don't exit this play until the machines are reachable (they might still be booting up)
  remote_user: "{{ vm_username }}"
  wait_for_connection:
    delay: 5
    timeout: 300
  vars:
    ansible_pipelining: no