- name: Run tofu (Terraform replacement)
  delegate_to: localhost
  run_once: true
  block:
    - name: Run tofu init
      command: tofu init
      args:
        chdir: "{{ terraform_dir }}"

    - name: Run tofu plan
      command: tofu plan
      args:
        chdir: "{{ terraform_dir }}"

    - name: Run tofu apply
      command: tofu apply -auto-approve
      args:
        chdir: "{{ terraform_dir }}"

- name: Don't exit this play until the machines are reachable (they might still be booting up)
  remote_user: "{{ vm_username }}"
  wait_for_connection:
    delay: 5
    timeout: 300
  vars:
    ansible_pipelining: no