version: "3.8"

services:
  # WhoAmI - For Testing and Troubleshooting
  whoami:
    image: traefik/whoami
    env_file: /var/data/stack/whoami/.env
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=cloud-public"
        # HTTP Routers
        - "traefik.http.routers.whoami-rtr.entrypoints=websecure"
        - "traefik.http.routers.whoami-rtr.rule=Host(`whoami.$DOMAIN_NAME`)"
        # HTTP Services
        - "traefik.http.routers.whoami-rtr.service=whoami-svc"
        - "traefik.http.services.whoami-svc.loadbalancer.server.port=80"
    networks:
      - cloud-public

networks:
  cloud-public:
    external: true
