---
- hosts: proxmox_servers
  gather_facts: no
  become: no

  tasks:
    # Provision terraform base
    - { import_role: { name: infrastructure/terraform-provision-base }, tags: [ infrastructure, proxmox ], become: no }

    # Provision terraform proxmox config
    - { import_role: { name: infrastructure/terraform-provision-proxmox }, tags: [ infrastructure, proxmox ], become: no }

- hosts: swarm_nodes
  gather_facts: no
  become: no

  tasks:
    # Provision terraform node config
    - { import_role: { name: infrastructure/terraform-provision-node }, tags: [ infrastructure, proxmox ], become: no }

    # Run Terraform
    - { import_role: { name: infrastructure/terraform-run }, tags: [ infrastructure, proxmox ], become: no }

