---
- name: Destroy cluster nodes
  hosts: proxmox_servers
  gather_facts: false
  become: false

  tasks:
    - name: DESTROY TEMPLATE
      ansible.builtin.pause:
        prompt: |
          Please confirm you want to destroy provisioned Proxmox Templates!
          DATA LOSS MAY OCCUR.
          Press return to continue. Press Ctrl+c and then "a" to abort'

    - name: Destroy cluster node VM's
      ansible.builtin.import_role: { name: destroy/remove-nodes } # noqa role-name[path]
      become: false

    - name: Cleanup Terraform files
      ansible.builtin.import_role: { name: destroy/tofu-cleanup } # noqa role-name[path]
      become: false
