---
- hosts: proxmox_servers
  gather_facts: no
  become: no

  tasks:
    - name: Combine configuration
      include_tasks: common/tasks/combine-config.yml
    - name: DESTROY TEMPLATE
      pause:
        prompt: |
          Please confirm you want to destroy provisioned Proxmox Templates! 
          DATA LOSS MAY OCCUR.
          Press return to continue. Press Ctrl+c and then "a" to abort'
    # Create proxmox base templates
    - { import_role: { name: infrastructure/infrastructure-destroy }, tags: [ proxmox-destroy ], become: no }

    - name: "Delete the terraform dir once destroyed: {{ terraform_dir }}"
      delegate_to: localhost
      run_once: true
      file:
        path: "{{ terraform_dir }}"
        state: absent