---
- hosts: cluster_nodes
  gather_facts: yes
  remote_user: "{{ cluster_node.username }}"
  become: yes

  tasks:
    - name: add the hosts in the group to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item]['ansible_host'] }} {{item}}"
        state: present
      with_items:
        - "{{ play_hosts }}"

    - name: prevent cloud-init from overwriting /etc/hosts
      lineinfile:
        dest: /etc/cloud/cloud.cfg
        regex: "update_etc_hosts"
        state: absent

    # Docker Provision
    - {
      include_role: { name: provision/provision-docker },
      tags: [ infrastructure, node, dependencies, docker ],
      when: runtime.type == 'docker'
    }

    # Kubernetes Provision
    - {
      include_role: { name: provision/provision-kubernetes },
      tags: [ infrastructure, node, dependencies, kubernetes ],
      when: runtime.type == 'kubernetes'
    }
