---
- hosts: proxmox_servers
  gather_facts: no
  become: no

  tasks:
    - name: Combine configuration
      include_tasks: common/tasks/combine-config.yml

    # Provision terraform base
    - { import_role: { name: infrastructure/terraform-provision-base }, tags: [ infrastructure, proxmox ], become: no }

    # Provision base cloud images
    - { import_role: { name: infrastructure/terraform-provision-cloud-image }, tags: [ infrastructure, proxmox ], become: no }

- hosts: swarm_nodes
  gather_facts: no
  become: no

  tasks:
    - block:
        - name: "Check build hosts"
          debug:
            msg: "No proxmox hosts defined, ending job"
        - meta: end_play
      when: (groups.proxmox_servers | length) < 1
      run_once: true

    # Provision terraform node config
    - { import_role: { name: infrastructure/terraform-provision-node }, tags: [ infrastructure, proxmox ], become: no }

    # Run Terraform
    - { import_role: { name: infrastructure/terraform-run }, tags: [ infrastructure, proxmox ], become: no }