---
- name: Provision cluster nodes
  hosts: cluster_nodes
  gather_facts: true
  remote_user: "{{ cluster_node.username }}"
  become: true

  tasks:
    - name: Add the hosts in the group to /etc/hosts
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        regexp: ".*{{ item }}$"
        line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
        state: present
      with_items:
        - "{{ play_hosts }}"

    - name: Prevent cloud-init from overwriting /etc/hosts
      ansible.builtin.lineinfile:
        dest: /etc/cloud/cloud.cfg
        regex: "update_etc_hosts"
        state: absent

    - name: Docker Provision
      ansible.builtin.include_role:
        name: provision/provision-docker # noqa role-name[path]
      when: runtime.type == 'docker'

    - name: Kubernetes Provision
      ansible.builtin.include_role:
        name: provision/provision-kubernetes # noqa role-name[path]
      when: runtime.type == 'kubernetes'
