---
- name: Set up base for proxmox orchestration
  hosts: proxmox_servers
  gather_facts: false
  become: false

  tasks:
    - name: Provision terraform base
      ansible.builtin.import_role:
        name: build/terraform-provision-base # noqa role-name[path]
      become: false

    - name: Provision base cloud images
      ansible.builtin.import_role:
        name: build/terraform-provision-cloud-image # noqa role-name[path]
      become: false

- name: Set up cluster host terraform files
  hosts: cluster_nodes
  strategy: linear
  gather_facts: false
  become: false

  tasks:
    - name: Verify we have proxmox hosts defined before running this job # noqa run-once[task]
      when: (groups.proxmox_servers | length) < 1
      run_once: true
      block:
        - name: "Check build hosts"
          ansible.builtin.debug:
            msg: "No proxmox hosts defined, ending job"
        - name: "End job"
          ansible.builtin.meta: end_play

    - name: Provision terraform node config
      ansible.builtin.import_role:
        name: build/terraform-provision-node # noqa role-name[path]
      become: false

- name: Create cluster
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: Run Terraform
      ansible.builtin.import_role:
        name: build/terraform-run # noqa role-name[path]
      become: false
