---
- hosts: swarm_nodes[0]
  gather_facts: yes
  become: yes
  remote_user: "{{ vm_username }}"

  environment:
    DOMAIN_NAME: "{{ dns_domain }}"

  tasks:
    - name: Combine configuration
      include_tasks: common/tasks/combine-config.yml

    # Setup baseline networking
    - name: Create swarm networks
      block:
        - name: Create cloud-public network
          docker_network:
            name: cloud-public
            scope: swarm
            driver: overlay
            attachable: yes

    # Deploy Stacks
    - { import_role: { name: stack-deploy }, tags: [ stack ], vars: { recipe: traefik } }

    - { import_role: { name: stack-deploy }, tags: [ stack ], vars: { recipe: cloudflared } }

    - { import_role: { name: stack-deploy }, tags: [ stack ], vars: { recipe: authentik } }

    - { import_role: { name: stack-deploy }, tags: [ stack ], vars: { recipe: whoami } }
