---
- name: Deploy stack
  hosts: cluster_nodes[0]
  gather_facts: true
  become: true
  remote_user: "{{ cluster_node.username }}"

  environment:
    DOMAIN_NAME: "{{ dns_domain }}"

  tasks:
    - name: Deploy infra related services
      ansible.builtin.import_role:
        name: deploy/deploy-infra-services # noqa role-name[path]

    ## Deploy Supporting Stacks
    # Authentik for auth
    - { import_role: { name: stack-deploy }, tags: [ stack ], vars: { recipe: authentik } }

    # Portainer for container management
    - { import_role: { name: stack-deploy }, tags: [ stack ], vars: { recipe: portainer } }

    # Debug container
    - { import_role: { name: stack-deploy }, tags: [ stack ], vars: { recipe: whoami } }

    ## Service Recipes
    - { import_role: { name: stack-deploy }, tags: [ stack ], vars: { recipe: actual_budget } }

    - { import_role: { name: stack-deploy }, tags: [ stack ], vars: { recipe: gitea } }

    - { import_role: { name: stack-deploy }, tags: [ stack ], vars: { recipe: homepage } }

    - { import_role: { name: stack-deploy }, tags: [ stack ], vars: { recipe: overseerr } }
