---
- hosts: swarm_nodes[0]
  gather_facts: yes
  become: yes
  remote_user: "{{ vm_username }}"

  environment:
    DOMAIN_NAME: "{{ dns_domain }}"

  tasks:
    # Combine recipe fact with defaults fact. output fact: recipes
    - name: Combine configuration
      include_tasks: common/tasks/combine-config.yml

    # Setup baseline networking
    - name: Create swarm networks
      block:
        - name: Create cloud-public network
          docker_network:
            name: cloud-public
            scope: swarm
            driver: overlay
            attachable: yes

    - name: Log into DockerHub (to avoid ratelimits)
      docker_login:
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password}}"
      when:
        - docker_hub_username is defined
        - docker_hub_password is defined

    ## Deploy Supporting Stacks
    # Traefik Router
    - { import_role: { name: stack-deploy }, tags: [ stack ], vars: { recipe: traefik } }

    # Cloudflare tunnel
    - { import_role: { name: stack-deploy }, tags: [ stack ], vars: { recipe: cloudflared } }

    # Authentik for auth
    - { import_role: { name: stack-deploy }, tags: [ stack ], vars: { recipe: authentik } }

    # Debug container
    - { import_role: { name: stack-deploy }, tags: [ stack ], vars: { recipe: whoami } }
