- name: Ensure Gluster brick and mount directories exist.
  file: "path={{ item }} state=directory mode=0775"
  with_items:
    - "{{ gluster_brick_dir }}"
    - "{{ gluster_mount_dir }}"

- name: "Create and mount partition on data drive"
  block:
    - parted:
        device: /dev/sdb
        number: 1
        flags: [ lvm ]
        state: present

    - filesystem:
        fstype: ext4
        dev: /dev/sdb1

    - mount:
        fstype: ext4
        src: /dev/sdb1
        path: "{{ gluster_brick_dir }}"
        state: mounted

- name: install gluster packages (try to get apt lock for up to 10 min)
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - glusterfs-client
      - glusterfs-server
  register: _result
  until: _result.failed == false
  retries: 30 # retry X times
  delay: 5     # pause for X sec b/w each call

- name: Start service glusterd, if not started
  ansible.builtin.service:
    name: glusterd
    state: started
  register: _result
  until: _result.failed == false
  retries: 30 # retry X times
  delay: 5     # pause for X sec b/w each call

- name: Configure Gluster volume
  gluster_volume:
    state: present
    name: "{{ gluster_brick_name }}"
    brick: "{{ gluster_brick_dir }}"
    replicas: "{{ play_hosts | length }}"
    cluster: "{{ play_hosts | join(',') }}"
    host: "{{ inventory_hostname }}"
    force: yes
  run_once: true

- name: Ensure Gluster volume is mounted.
  mount:
    name: "{{ gluster_mount_dir }}"
    src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted