# These are the physical proxmox hosts that you will be using to deploy your cluster nodes on. There can be one
# or many of these defined.
example:
  children:
    proxmox_servers:
      hosts:
        proxmox-1:
          ansible_host: 192.168.1.10
          ansible_user: root
          template_vm_id: 5002
        proxmox-2:
          ansible_host: 192.168.1.11
          ansible_user: root
          template_vm_id: 5003

    # These are the swarm nodes that will be built and deployed to your proxmox hosts
    # There first node defined MUST have a `cluster_role` of `master`. Ansible will run the bootstrapping of the
    # cluster and the distributed storage on this node.
    cluster_nodes:
      hosts:
        node-1:
          vm_id: 3001
          ansible_host: 192.168.1.211         # The IP address to assign to the node VM
          mac: 52:54:00:31:02:11              # The MAC Address to assign to the node VM
          proxmox_node: proxmox-1             # The promox node (listed above) to deploy the VM to
          cluster_role: master                # The cluster_role of this node in the docker swarm/kubernetes cluster (master/worker). This first node must be a master\
          keepalived_priority: 101            # The priority order for keepalived
        node-2:
          vm_id: 3002
          ansible_host: 192.168.1.212
          mac: 52:54:00:31:02:12
          proxmox_node: proxmox-2
          cluster_role: master
          keepalived_priority: 102
        node-3:
          vm_id: 3003
          ansible_host: 192.168.1.213
          mac: 52:54:00:31:02:13
          proxmox_node: proxmox-1
          cluster_role: master
          keepalived_priority: 103
        node-4:
          vm_id: 3004
          ansible_host: 192.168.1.214
          mac: 52:54:00:31:02:14
          proxmox_node: proxmox-2
          cluster_role: worker
          keepalived_priority: 104
        node-5:
          vm_id: 3005
          ansible_host: 192.168.1.215
          mac: 52:54:00:31:02:15
          proxmox_node: proxmox-1
          cluster_role: worker
          keepalived_priority: 105