---
- name: Have we partitioned sdb1?
  ansible.builtin.shell: "fdisk -l | grep sdb1"
  register: _sdb1_partitioned
  ignore_errors: true
  changed_when: true

- name: Enable ceph dashboard in microceph
  when: not _sdb1_partitioned.rc == 0
  block:
    - name: "Create a new ext4 primary partition on data disk"
      community.general.parted:
        device: /dev/sdb
        number: 1
        state: present
        part_end: "100%"
        resize: true

    - name: Define file system for the disk
      community.general.filesystem:
        fstype: ext4
        dev: "/dev/sdb1"

    - name: "Mount data disk"
      ansible.posix.mount:
        path: /mnt/appdata
        src: /dev/sdb1
        fstype: ext4
        state: mounted

- name: "Ensure storage root_dir exists with correct permissions"
  ansible.builtin.file:
    path: "/mnt/appdata/data"
    state: directory
    mode: "0777"
    owner: "{{ storage.owner }}"
    group: "{{ storage.group }}"
    recurse: true

- name: Install NFS Packages.
  ansible.builtin.apt:
    name:
      - nfs-common
      - nfs-kernel-server
    state: present

- name: Ensure required entries are made to exports file.
  ansible.builtin.lineinfile:
    path: /etc/exports
    state: present
    line: "{{ item }}"
  with_items:
    - '"/mnt/appdata/data" *(rw,sync,no_subtree_check,no_root_squash,insecure)'

- name: Restart nfs-kernel-server.service
  ansible.builtin.systemd:
    daemon_reload: true
    state: started
    name: nfs-kernel-server.service

- name: Re-export the share
  ansible.builtin.command: exportfs -rav
  changed_when: true
