- name: add ubuntu docker apt-key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  register: _result
  until: _result.failed == false
  retries: 30 # retry X times
  delay: 5     # pause for X sec b/w each call

- name: install ubuntu docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ proxmox_vm_ubuntu_version }} stable
    state: present
  register: _result
  until: _result.failed == false
  retries: 30 # retry X times
  delay: 5     # pause for X sec b/w each call

- name: install docker packages (try to get apt lock for up to 10 min)
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3-docker
      - python3-jsondiff
  register: _result
  until: _result.failed == false
  retries: 30 # retry X times
  delay: 5     # pause for X sec b/w each call

- name: init the swarm on the first node
  docker_swarm:
    state: present
  register: docker_swarm_init
  delegate_to: "{{ play_hosts[0] }}"
  run_once: true

- set_fact:
    worker_token: "{{ docker_swarm_init.swarm_facts.JoinTokens.Worker }}"
    manager_token: "{{ docker_swarm_init.swarm_facts.JoinTokens.Manager }}"
    master_ip: "{{ hostvars[play_hosts[0]].ansible_host }}"

- name: join the swarm on the remaining nodes as a master
  docker_swarm:
    advertise_addr: "{{ ansible_host }}"
    remote_addrs: "{{ master_ip }}"
    join_token: "{{ manager_token }}"
    state: join
  when:
    - inventory_hostname != play_hosts[0]
    - swarm_role == "master"

- name: join the swarm on the remaining nodes as a worker
  docker_swarm:
    advertise_addr: "{{ ansible_host }}"
    remote_addrs: "{{ master_ip }}"
    join_token: "{{ worker_token }}"
    state: join
  when:
    - inventory_hostname != play_hosts[0]
    - swarm_role == "worker"